condition('C11', 'EV7').
condition('C10', 'EV9').
condition('C13', 'EV16').
condition('C12', 'EV4').
condition('C15', 'EV3').
condition('C14', 'EV6').
condition('C1', 'EV13').
condition('C2', 'EV15').
condition('C3', 'EV17').
condition('C4', 'EV14').
condition('C5', 'EV1').
condition('C6', 'EV11').
condition('C7', 'EV12').
condition('C8', 'EV10').
condition('C9', 'EV5').
condition('C16', 'EV2').
actionSource('AS39', ['C6'], [], ['A1'], [], [], '', '', '', '', '').
actionSource('AS37', [], [], ['A10'], [], ['S23'], '', '', '', '', '').
actionSource('AS38', ['C5'], [], ['A13'], [], ['S12'], '', '', '', '', '').
actionSource('AS35', ['C11'], [], ['A11'], ['S24'], [], '', '', '', '', '').
actionSource('AS36', [], [], ['A16'], [], ['S24'], '', '', '', '', '').
actionSource('AS33', ['C1'], [], ['A15'], ['S12'], [], '', '', '', '', '').
actionSource('AS34', [], [], ['A5'], [], ['S12'], '', '', '', '', '').
actionSource('AS31', ['C10'], [], ['A14'], ['S13'], [], '', '', '', '', '').
actionSource('AS32', [], [], ['A1'], [], ['S13'], '', '', '', '', '').
actionSource('AS30', [], [], ['A14'], [], ['S25'], '', '', '', '', '').
actionSource('AS48', ['C9'], [], ['A13'], [], [], '', '', '', '', '').
actionSource('AS49', [], [], ['A8'], [], ['S3'], '', '', '', '', '').
actionSource('AS46', [], [], ['A13'], [], ['S3'], '', '', '', '', '').
actionSource('AS47', ['C12'], [], ['A10'], [], ['S20'], '', '', '', '', '').
actionSource('AS44', ['C12'], [], ['A1'], [], ['S17'], '', '', '', '', '').
actionSource('AS45', ['C13'], [], ['A3'], [], [], '', '', '', '', '').
actionSource('AS42', ['C8'], [], ['A5'], [], [], '', '', '', '', '').
actionSource('AS43', [], [], ['A13'], [], ['S12'], '', '', '', '', '').
actionSource('AS40', [], [], ['A10'], [], ['S4'], '', '', '', '', '').
actionSource('AS41', ['C5'], [], ['A6'], [], ['S15'], '', '', '', '', '').
actionSource('AS1', [], [], ['A1'], [], ['S23','S24'], '', '', '', '', '( S23 AND S24 )').
actionSource('AS2', [], [], ['A2'], [], ['S25','S26'], '', '', '', '', '( S25 AND S26 )').
actionSource('AS3', [], [], ['A3'], [], ['S1','S2'], '', '', '', '', '( S1 AND S2 )').
actionSource('AS4', [], [], ['A3'], [], ['S3','S27'], '', '', '', '', '( S3 AND S27 )').
actionSource('AS5', [], [], ['A4'], [], ['S4','S5'], '', '', '', '', '( S4 AND S5 )').
actionSource('AS6', ['C16'], [], ['A5'], [], [], '', '', '', '', '').
actionSource('AS19', [], [], ['A7'], [], ['S10','S16'], '', '', '', '', '( S10 AND S16 )').
actionSource('AS7', [], [], ['A6'], [], ['S2','S7'], '', '', '', '', '( S2 AND S7 )').
actionSource('AS8', ['C4'], [], ['A7'], [], [], '', '', '', '', '').
actionSource('AS17', [], [], ['A12'], [], ['S27','S12'], '', '', '', '', '( S27 AND S12 )').
actionSource('AS9', [], [], ['A8'], [], ['S9','S8'], '', '', '', '', '( S9 AND S8 )').
actionSource('AS18', ['C12'], [], ['A3'], [], [], '', '', '', '', '').
actionSource('AS15', [], [], ['A11'], [], ['S12','S8'], '', '', '', '', '( S12 AND S8 )').
actionSource('AS59', ['C12'], [], ['A6'], [], ['S21'], '', '', '', '', '').
actionSource('AS16', ['C4'], [], ['A3'], [], [], '', '', '', '', '').
actionSource('AS13', [], [], ['A5'], [], ['S11','S14'], '', '', '', '', '( S11 AND S14 )').
actionSource('AS57', ['C14'], [], ['A6'], [], [], '', '', '', '', '').
actionSource('AS14', ['C15'], [], ['A10'], [], [], '', '', '', '', '').
actionSource('AS58', [], [], ['A13'], [], ['S24'], '', '', '', '', '').
actionSource('AS11', [], [], ['A5'], [], ['S8','S25'], '', '', '', '', '( S8 AND S25 )').
actionSource('AS55', [], [], ['A12'], [], ['S7'], '', '', '', '', '').
actionSource('AS12', ['C7'], [], ['A6'], [], [], '', '', '', '', '').
actionSource('AS56', ['C15'], [], ['A9'], [], ['S19'], '', '', '', '', '').
actionSource('AS53', ['C7'], [], ['A2'], [], ['S8'], '', '', '', '', '').
actionSource('AS10', ['C4'], [], ['A9'], [], [], '', '', '', '', '').
actionSource('AS54', ['C4'], [], ['A16'], [], [], '', '', '', '', '').
actionSource('AS51', ['C14'], [], ['A13'], [], [], '', '', '', '', '').
actionSource('AS52', [], [], ['A4'], [], ['S22'], '', '', '', '', '').
actionSource('AS50', ['C13'], [], ['A13'], [], ['S18'], '', '', '', '', '').
actionSource('AS28', [], [], ['A2'], [], ['S12'], '', '', '', '', '').
actionSource('AS29', ['C9'], [], ['A5'], ['S25'], [], '', '', '', '', '').
actionSource('AS26', [], [], ['A3'], [], ['S16'], '', '', '', '', '').
actionSource('AS27', ['C8'], [], ['A13'], ['S13'], [], '', '', '', '', '').
actionSource('AS24', [], [], ['A3'], [], ['S6'], '', '', '', '', '').
actionSource('AS25', ['C6'], [], ['A14'], ['S17'], [], '', '', '', '', '').
actionSource('AS22', [], [], ['A10'], [], ['S13'], '', '', '', '', '').
actionSource('AS23', ['C6'], [], ['A9'], ['S5'], [], '', '', '', '', '').
actionSource('AS20', ['C13'], [], ['A10'], [], [], '', '', '', '', '').
actionSource('AS21', ['C5'], [], ['A11'], ['S12'], [], '', '', '', '', '').
actionSource('AS60', ['C10'], [], ['A17'], [], [], '', '', '', '', '').
entity('E1', 'RCMVAR_the_steering_wheel_angle').
entity('E2', 'RCMVAR_the_NoSailing_requests').
entity('E3', 'RCMVAR_the_LSC').
entity('E4', 'RCMVAR_the_brake_fault_state').
entity('E5', 'RCMVAR_the_sailing_termination').
entity('E6', 'RCMVAR_the_standstill_request_flag').
entity('E7', 'RCMVAR_the_vehicle_speed_quality_factor').
entity('E8', 'RCMVAR_the_sailing_request').
entity('E9', 'RCMVAR_the_transmission_error').
entity('E10', 'RCMVAR_the_quality_signal').
entity('E11', 'RCMVAR_the_IDC_inhibitor').
entity('E12', 'RCMVAR_the_sailing_inhibitor').
entity('E13', 'RCMVAR_the_defined_position').
entity('E14', 'RCMVAR_the_engine_error').
entity('E15', 'RCMVAR_the_brake_pedal').
entity('E16', 'RCMVAR_the_vehicle_speed_setpoint').
action('A10', 'EV1').
action('A11', 'EV2').
action('A12', 'EV3').
action('A13', 'EV4').
action('A14', 'EV5').
action('A15', 'EV6').
action('A16', 'EV7').
action('A17', 'EV8').
action('A1', 'EV9').
action('A2', 'EV10').
action('A3', 'EV11').
action('A4', 'EV12').
action('A5', 'EV13').
action('A6', 'EV14').
action('A7', 'EV15').
action('A8', 'EV16').
action('A9', 'EV17').
scope('S1', 'StartUP', 'EV15').
scope('S2', 'EndUP', 'EV15').
scope('S3', 'EndUP', 'EV4').
scope('S4', 'EndUP', 'EV13').
scope('S5', 'EndUP', 'EV2').
scope('S6', 'StartUP', 'EV2').
scope('S7', 'EndUP', 'EV14').
scope('S8', 'StartUP', 'EV14').
scope('S9', 'StartUP', 'EV17').
scope('S10', 'StartUP', 'EV1').
scope('S11', 'EndUP', 'EV1').
scope('S12', 'EndUP', 'EV11').
scope('S13', 'StartUP', 'EV11').
scope('S14', 'StartUP', 'EV3').
scope('S15', 'EndUP', 'EV10').
scope('S16', 'EndUP', 'EV16').
scope('S17', 'StartUP', 'EV16').
scope('S18', 'StartUP', 'EV6').
scope('S19', 'EndUP', 'EV6').
scope('S20', 'EndUP', 'EV5').
scope('S21', 'EndUP', 'EV8').
scope('S22', 'StartUP', 'EV7').
scope('S23', 'StartUP', 'EV9').
scope('S24', 'EndUP', 'EV9').
scope('S25', 'StartUP', 'EV12').
scope('S26', 'EndUP', 'EV12').
scope('S27', 'StartUP', 'EV4').
event('EV1', 'E15', value('Atomic', 'RCMVAL_True')).
event('EV2', 'E16', value('Atomic', 'RCMVAL_True')).
event('EV3', 'E7', value('Atomic', 'RCMVAL_True')).
event('EV4', 'E2', value('Atomic', 'RCMVAL_True')).
event('EV5', 'E3', value('Atomic', 'RCMVAL_True')).
event('EV6', 'E9', value('Atomic', 'RCMVAL_True')).
event('EV7', 'E10', value('Atomic', 'RCMVAL_True')).
event('EV8', 'E6', value('Atomic', 'RCMVAL_False')).
event('EV9', 'E6', value('Atomic', 'RCMVAL_True')).
event('EV10', 'E5', value('Atomic', 'RCMVAL_True')).
event('EV11', 'E8', value('Atomic', 'RCMVAL_True')).
event('EV12', 'E1', value('Atomic', 'RCMVAL_True')).
event('EV13', 'E11', value('Atomic', 'RCMVAL_True')).
event('EV14', 'E12', value('Atomic', 'RCMVAL_True')).
event('EV15', 'E13', value('Atomic', 'RCMVAL_True')).
event('EV16', 'E14', value('Atomic', 'RCMVAL_True')).
event('EV17', 'E4', value('Atomic', 'RCMVAL_True')).
